### ISSUE TITLE
phase out using <table> for layout, using divs instead

### ISSUE THREAD

**Issue by dataf3l** [jpaulm/jpaulm.github.io#1]
using tables is discouraged, in favour of divs,
so we can have nice reponsive design.
this is because tables take longer to render.

https://github.com/jpaulm/jpaulm.github.io/blob/05e4f2887fb62d7d064c89f923ba2f1e783ce464/fbp/index.shtml#L142

**Comment by dataf3l** [comment]
So I guess the main issue would be "make site responsive"

**Comment by jpaulm** [comment]
Done!  table tag wasn't doing anything useful after I deleted the Count cgi call!  Thanks

**Comment by dataf3l** [comment]
Awesome!
